service:
- docker
env:
  global:
  - TERM=dumb
language: java
jdk: oraclejdk8
addons:
  apt:
    update: true
    packages:
    - curl
    - jq
    - bash
    - python-pip
    - docker-ce
install: true
before_install:
- sudo pip install httpie docker-compose >/dev/null 2>&1
- source <(curl -fsSL https://raw.github.com/daggerok/bash-functions/master/main.bash)
- stop_any 80 8000 8080 8081 8082 8083 8001 8002 8003
- echo "org.gradle.console=auto" > gradle.properties
script:
- ./gradlew clean :docs:asciidoctor -b build.gradle || true
- ./gradlew -S >/dev/null
- ./gradlew --stop || true
- mkdir -p ~/.m2:/root/.m2 ~/.gradle:/root/.gradle
- docker-compose build
- docker-compose run -v ~/.m2:/root/.m2 -v ~/.gradle:/root/.gradle build
- docker-compose run all
- docker-compose logs -f -t &
- sleep 35
- wait_for 8001 8002 8003
- http -a clientId:secret
  --form post :8001/oauth/token
  grant_type=password
  username=usr
  password=pwd
- access_token=$(http -a clientId:secret --form post :8001/oauth/token grant_type=password username=usr password=pwd | jq .access_token)
- access_token="${access_token%\"}" # remove prefixed (left) quote
- access_token="${access_token#\"}" # remove suffix (right) quote
- http -a clientId:secret --form post :8001/oauth/check_token token=$access_token
- http :8002/ Authorization:"Bearer $access_token"
- docker-compose stop
- docker-compose down -v
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
